- name: Test script
        run:
          result=$(shell_exec './script.sh test1.txt test2.txt')
          
          if [[ "$result" == *"Людей в test1.txt - 3"* ]]; then
            echo "Test passed"
          else
            echo "Test failed"
            exit 1
          fi
          
          if [[ "$result" == *"Людей в test2.txt - 2"* ]]; then
            echo "Test passed"
          else
            echo "Test failed"
            exit 1
          fi
          
          if [[ "$result" == *"Одинаково людей"* ]]; then
            echo "Test passed"
          else
            echo "Test failed"
            exit 1
          fi
